import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
    faArrowAltCircleUp,
    faArrowsRotate,
    faAngleDown,
    faCheckCircle,
    faCloudArrowDown,
    faCog,
    faEdit,
    faEye,
    faEyeSlash,
    faHome,
    faPause,
    faPen,
    faPlay,
    faPlus,
    faRocket,
    faRotate,
    faSave,
    faSearch,
    faSignOutAlt,
    faStop,
    faTerminal,
    faTimes,
    faTrash,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faArrowAltCircleUp,
    faArrowsRotate,
    faAngleDown,
    faCheckCircle,
    faCloudArrowDown,
    faCog,
    faEdit,
    faEye,
    faEyeSlash,
    faHome,
    faPause,
    faPen,
    faPlay,
    faPlus,
    faRocket,
    faRotate,
    faSave,
    faSearch,
    faSignOutAlt,
    faStop,
    faTerminal,
    faTimes,
    faTrash,
);

export { FontAwesomeIcon };
